name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm install

      - name: Build the web bundle
        run: npm run build

      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: anoop901/anoop901.github.io
          BRANCH: master
          FOLDER: dist
          TARGET_FOLDER: graphical-functional-programming
